# Banco
quarkus.datasource.db-kind=mysql

# Schema (Flyway aplica, Hibernate valida)
quarkus.flyway.migrate-at-start=true
quarkus.hibernate-orm.database.generation=validate
%dev.quarkus.hibernate-orm.log.sql=true

# Swagger (em /q/docs)
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=docs
